version: '3'

vars:
  DB_NAME: conduit

env:
  DB_DSN: postgres://postgres:postgres@localhost:5432/{{.DB_NAME}}?sslmode=disable
  JWT_SECRET: conduit-super-secret-key-min-32-chars-long
  JWT_ISSUER: conduit

tasks:
  docker:postgres:start:
    desc: Start a Postgres server via docker compose
    cmds:
      - docker compose up -d db

  db:setup:
    desc: Setup the database
    cmds:
      - PGPASSWORD=postgres psql -U postgres -h localhost -c "CREATE DATABASE {{.DB_NAME}};"

  db:migrations:up:
    desc: Runs up migrations
    cmds:
      - migrate -path ./migrations -database ${DB_DSN} up

  server:start:
    desc: Starts the API server (includes postgres and migrations)
    cmds:
      - docker compose up -d db
      - sleep 2
      - PGPASSWORD=postgres psql -U postgres -h localhost -c "CREATE DATABASE {{.DB_NAME}};" || true
      - migrate -path ./migrations -database ${DB_DSN} up
      - go run ./cmd/api {{.CLI_ARGS}}

  install:dependencies:
    desc: Install Go-specific tools
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
      - go install gotest.tools/gotestsum@v1.12.3
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.18.2
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0

  audit:
    desc: Run quality control audits
    cmds:
      - go mod tidy
      - go mod verify
      - go fmt ./...
      - golangci-lint run --tests=false
      - govulncheck ./...

  test:
    desc: Run all Go unit tests
    cmds:
      - gotestsum -- -coverprofile=coverage.out -coverpkg=./...  ./... {{.CLI_ARGS}}
